# Generated by Django 4.2.6 on 2023-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
